version: 2

models:
  - name: sl_products
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: product_name
        tests:
          - not_null
          # - unique

      - name: category
        tests:
          - not_null

      - name: clean_price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: sl_customers
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: customer_name
        tests:
          - not_null
          # - unique

      - name: customer_email
        tests:
          - not_null
          # - unique

      - name: customer_country
        tests:
          - not_null

  - name: sl_orders
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: order_date
        tests:
          - not_null

      - name: customer_id
        tests:
          - relationships:
              to: ref('sl_customers')
              field: id

      - name: status
        tests:
          - not_null
          - accepted_values:
              values:
                - completed
                - pending
                - cancelled
                - processing
                - unknown
                - invalid_status

  - name: sl_order_products
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: order_id
        tests:
          - relationships:
              to: ref('sl_orders')
              field: id

      - name: product_id
        tests:
          - relationships:
              to: ref('sl_products')
              field: id
              config:
                severity: warn
                store_failures: true

      - name: quantity
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: unit_price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"