name: dbt CI

on:
  push:
    branches: [ main ]

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install dbt-postgres

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > profiles.yml << EOF
          etl:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${{ secrets.DB_HOST }}
                user: ${{ secrets.DB_USER }}
                password: ${{ secrets.DB_PASSWORD }}
                port: 5432
                dbname: ${{ secrets.DB_NAME }}
                schema: analytics
                threads: 4
          EOF

      - name: dbt debug
        run: dbt debug --profiles-dir .

      - name: dbt build
        run: dbt build --profiles-dir .